version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: GaitTST
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./app_users.csv:/docker-entrypoint-initdb.d/app_users.csv

  app:
    build:
      context: .
      dockerfile: Dockerfile   # Dockerfile for your IntelliJ/Spring Boot app (at the project root)
    container_name: intellij_app
    restart: always
    depends_on:
      - db
      - blazegraph
    environment:
      SPRING_APPLICATION_NAME: Gait
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/GaitTST
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      # Liquibase manages schema; disable Hibernate auto DDL
      # SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_STRING_ABC123
      JWT_EXPIRATION_MS: 86400000
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog/db.changelog-master.xml
      # Configure Blazegraph endpoint using Docker service name:
      BLAZEGRAPH_ENDPOINT: http://blazegraph:9999/blazegraph/namespace/kb/sparql
    ports:
      - "8080:8080"

  blazegraph:
    build:
      context: ./blazegraph   # This folder contains the Dockerfile for Blazegraph and your blazegraph.jar
      dockerfile: Dockerfile
    container_name: blazegraph
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - blazegraph_data:/var/lib/blazegraph/data

volumes:
  pgdata:
  blazegraph_data:
