version: "3.8"

services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: GaitTST
    ports:
      - "5432:5432"
    volumes:
      # Persist PostgreSQL data
      - pgdata:/var/lib/postgresql/data
      # Mount the SQL initialization script (ensure init.sql has the proper table definitions)
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # Mount the CSV file so that it’s available to the init script
      - ./app_users.csv:/docker-entrypoint-initdb.d/app_users.csv

  app:
    build: .
    container_name: intellij_app
    restart: always
    depends_on:
      - db
    environment:
      # Application name
      SPRING_APPLICATION_NAME: Gait
      # Datasource configuration (note: use hostname 'db' to reference the database service)
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/GaitTST
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      # JWT configuration
      JWT_SECRET: CHANGE_THIS_TO_A_LONG_RANDOM_SECRET_STRING_ABC123
      JWT_EXPIRATION_MS: 86400000
      # Liquibase changelog location
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/changelog/db.changelog-master.xml
    ports:
      - "8080:8080"

volumes:
  pgdata:
